"""add customer profiles

Revision ID: af253c035900
Revises: 338a77784ed2
Create Date: 2026-05-07 14:44:09.336902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af253c035900'
down_revision: Union[str, Sequence[str], None] = '338a77784ed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=40), nullable=False),
    sa.Column('birth_day', sa.Date(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('pin_code', sa.String(length=40), nullable=False),
    sa.Column('style_notes', sa.Text(), nullable=False),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_profiles_email'), 'customer_profiles', ['email'], unique=True)
    op.create_index(op.f('ix_customer_profiles_id'), 'customer_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_profiles_id'), table_name='customer_profiles')
    op.drop_index(op.f('ix_customer_profiles_email'), table_name='customer_profiles')
    op.drop_table('customer_profiles')
    # ### end Alembic commands ###
