"""
Sales domain models.

Entity hierarchy
----------------
Customer ──────────────────────────── SaleBill ──► SaleBillLine
                                           │
                                           └──► SalePayment

Design decisions
----------------
* customer_id is nullable on SaleBill — walk-in (cash) sales require no
  registered customer. The service accepts an optional customer_id.
* invoice_number is auto-generated by the service (tenant-scoped sequence)
  and enforced unique by the composite DB constraint.
* SaleBill.status: "confirmed" | "cancelled"
  Bills are created directly in "confirmed" state — the atomic service
  validates stock before writing, so a confirmed bill always has stock.
* SaleBillLine.unit_cost records the cost at time-of-sale for COGS reporting;
  it comes from the StockBatch consumed, not the selling_price.
* SalePayment is created atomically with the bill in one transaction; if
  payment recording fails the entire sale is rolled back.
* loyalty_points on Customer: integer, accumulated by the service layer in
  future phases. Stored here so the model is complete from Phase 4.
* PaymentMode is defined separately from purchase.PaymentMode to allow the
  sales-side modes to diverge (e.g. add "loyalty_redemption") without
  coupling to the purchase domain.
"""
from __future__ import annotations

import uuid
from decimal import Decimal
from enum import StrEnum

from sqlalchemy import (
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
    Date,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base
from app.models.catalog import ProductVariant

_SCHEMA = "sales"
_AMT = Numeric(14, 2)
_QTY = Numeric(14, 4)
_TAX = Numeric(6, 4)


class SalePaymentMode(StrEnum):
    CASH          = "cash"
    BANK_TRANSFER = "bank_transfer"
    CHEQUE        = "cheque"
    UPI           = "upi"
    CARD          = "card"
    OTHER         = "other"


# ── Customer ──────────────────────────────────────────────────────────────────

class Customer(Base):
    """
    A registered buyer.

    Walk-in customers are recorded as NULL customer_id on SaleBill.
    loyalty_points is accumulated post-sale and redeemed in future phases.
    """

    __tablename__ = "customers"
    __table_args__ = (
        UniqueConstraint("tenant_id", "email", name="uq_sales_customers_tenant_email"),
        Index("ix_sales_customers_tenant", "tenant_id"),
        Index("ix_sales_customers_phone", "phone"),
        {"schema": _SCHEMA},
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True,
        default=uuid.uuid4,
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tenant.tenants.id", ondelete="CASCADE"),
        nullable=False,
    )
    name: Mapped[str] = mapped_column(String(250), nullable=False)
    email: Mapped[str | None] = mapped_column(String(254))
    phone: Mapped[str | None] = mapped_column(String(20))
    address: Mapped[str | None] = mapped_column(Text)
    loyalty_points: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    is_active: Mapped[bool] = mapped_column(nullable=False, server_default="1")

    bills: Mapped[list[SaleBill]] = relationship(back_populates="customer")

    def __repr__(self) -> str:
        return f"<Customer {self.name!r}>"


# ── SaleBill ──────────────────────────────────────────────────────────────────

class SaleBill(Base):
    """
    Header record for one sale transaction.

    invoice_number is auto-generated by the service (INV-{seq:06d}).
    total_amount = sum(line totals, incl. tax) - total_discount.
    tax_amount   = sum of all line tax amounts.
    total_discount = sum of all line discount amounts (line-level discounts only
                     in Phase 4; bill-level discounts added in later phases).
    """

    __tablename__ = "sale_bills"
    __table_args__ = (
        UniqueConstraint(
            "tenant_id", "invoice_number",
            name="uq_sales_bills_tenant_invoice",
        ),
        Index("ix_sales_bills_tenant", "tenant_id"),
        Index("ix_sales_bills_customer", "customer_id"),
        {"schema": _SCHEMA},
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True,
        default=uuid.uuid4,
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tenant.tenants.id", ondelete="CASCADE"),
        nullable=False,
    )
    customer_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey(f"{_SCHEMA}.customers.id", ondelete="SET NULL"),
    )
    location_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tenant.locations.id", ondelete="NO ACTION"),
        nullable=False,
    )
    bin_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("inventory.bins.id", ondelete="NO ACTION"),
        nullable=False,
    )

    invoice_number: Mapped[str] = mapped_column(String(50), nullable=False)
    bill_date: Mapped[str] = mapped_column(Date, nullable=False)
    total_amount: Mapped[Decimal] = mapped_column(_AMT, nullable=False, server_default="0")
    tax_amount: Mapped[Decimal] = mapped_column(_AMT, nullable=False, server_default="0")
    total_discount: Mapped[Decimal] = mapped_column(_AMT, nullable=False, server_default="0")
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, server_default="'confirmed'"
    )
    notes: Mapped[str | None] = mapped_column(Text)

    customer: Mapped[Customer | None] = relationship(back_populates="bills")
    lines: Mapped[list[SaleBillLine]] = relationship(
        back_populates="bill", cascade="all, delete-orphan"
    )
    payments: Mapped[list[SalePayment]] = relationship(
        back_populates="bill", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<SaleBill {self.invoice_number!r} ₹{self.total_amount}>"


# ── SaleBillLine ──────────────────────────────────────────────────────────────

class SaleBillLine(Base):
    """
    One SKU on a sale bill.

    selling_price  — price charged to the customer.
    unit_cost      — COGS cost at time-of-sale (from StockBatch.unit_cost).
    discount_amount — per-unit discount applied (0 if none).
    total_line_amount = quantity * (selling_price - discount_amount) * (1 + tax_rate)
    """

    __tablename__ = "sale_bill_lines"
    __table_args__ = (
        UniqueConstraint(
            "bill_id", "product_variant_id",
            name="uq_sales_lines_bill_variant",
        ),
        Index("ix_sales_lines_bill", "bill_id"),
        Index("ix_sales_lines_variant", "product_variant_id"),
        {"schema": _SCHEMA},
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True,
        default=uuid.uuid4,
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tenant.tenants.id", ondelete="CASCADE"),
        nullable=False,
    )
    bill_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey(f"{_SCHEMA}.sale_bills.id", ondelete="CASCADE"),
        nullable=False,
    )
    product_variant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("catalog.product_variants.id", ondelete="NO ACTION"),
        nullable=False,
    )

    quantity: Mapped[Decimal] = mapped_column(_QTY, nullable=False)
    selling_price: Mapped[Decimal] = mapped_column(_AMT, nullable=False)
    unit_cost: Mapped[Decimal] = mapped_column(_AMT, nullable=False, server_default="0")
    tax_rate: Mapped[Decimal] = mapped_column(_TAX, nullable=False, server_default="0")
    discount_amount: Mapped[Decimal] = mapped_column(_AMT, nullable=False, server_default="0")
    total_line_amount: Mapped[Decimal] = mapped_column(_AMT, nullable=False)

    bill: Mapped[SaleBill] = relationship(back_populates="lines")
    variant: Mapped[ProductVariant] = relationship()

    def __repr__(self) -> str:
        return (
            f"<SaleBillLine variant={self.product_variant_id} "
            f"qty={self.quantity} price={self.selling_price}>"
        )


# ── SalePayment ───────────────────────────────────────────────────────────────

class SalePayment(Base):
    """
    Payment collected for a SaleBill.

    Created atomically with the bill in the sales transaction. Multiple
    payments per bill are supported (split payment across modes).
    transaction_id holds the POS/UPI/card terminal reference number.
    """

    __tablename__ = "sale_payments"
    __table_args__ = (
        Index("ix_sales_payments_bill", "bill_id"),
        Index("ix_sales_payments_tenant", "tenant_id"),
        {"schema": _SCHEMA},
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True,
        default=uuid.uuid4,
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tenant.tenants.id", ondelete="CASCADE"),
        nullable=False,
    )
    bill_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey(f"{_SCHEMA}.sale_bills.id", ondelete="CASCADE"),
        nullable=False,
    )

    payment_date: Mapped[str] = mapped_column(Date, nullable=False)
    amount: Mapped[Decimal] = mapped_column(_AMT, nullable=False)
    payment_mode: Mapped[str] = mapped_column(String(20), nullable=False)
    transaction_id: Mapped[str | None] = mapped_column(String(100))
    notes: Mapped[str | None] = mapped_column(Text)

    bill: Mapped[SaleBill] = relationship(back_populates="payments")

    def __repr__(self) -> str:
        return f"<SalePayment {self.payment_mode} ₹{self.amount}>"
